name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
          VERSION: 1

        run: |
          docker build --tag revraymondbaguma/ray-gpt:latest --tag revraymondbaguma/ray-gpt:v${{ env.VERSION }} .
          docker push revraymondbaguma/ray-gpt:latest
          docker push revraymondbaguma/ray-gpt:v${{ env.VERSION }}

          VERSION=$((VERSION+1))
            echo "::set-env name=VERSION::$VERSION"

      - name: Pull latest Docker image
        run: docker pull revraymondbaguma/ray-gpt:latest

      - name: Cleanup
        run: |
          docker image prune -af
          docker container prune -f
